swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # History forward 
    right:
      sendkey: "LEFTALT+LEFT" # History back
    up:
      sendkey: "LEFTCTRL+LEFTMETA+DOWN" # Switch to next workspace
    down:
      sendkey: "LEFTCTRL+LEFTMETA+UP" # Switch to previous workspace
pinch:
  in:
    sendkey: "LEFTCTRL+KPPLUS" # Zoom in
  out:
    sendkey: "LEFTCTRL+KPMINUS" # Zoom out
