#!/hint/zsh

function fix-history() {
  local BADHISTFILE="${HISTFILE}_bad"
  mv "${HISTFILE}" "${BADHISTFILE}"
  strings "${BADHISTFILE}" > "${HISTFILE}"
  fc -R "${HISTFILE}"
  rm "${BADHISTFILE}"
}
