#!/bin/bash

if [[ -f '/etc/wsl.conf' ]]; then
    tmp="$(awk -F ' *= *' '/root/ {print $2}' '/etc/wsl.conf')"
    if [[ -z "${tmp}" ]]; then
        echo '/mnt/'
    else
        echo "${tmp}"
    fi
else
    echo '/mnt/'
fi

