#!/bin/zsh

_fzf_complete_asp() {
  local lbuf preview get_matches
  lbuf="$1"
  preview='pacman -Si {1}'
  get_matches='pacman -Slq'
  _fzf_complete --height="${FZF_TMUX_HEIGHT:=75%}" --multi --ansi \
    --bind='Ctrl-X:toggle-preview' \
    --no-hscroll --inline-info \
    --header='Ctrl-X to toggle package info' \
    --preview-window='right:wrap' \
    --preview="${preview}" -- "$@" < <(eval "${get_matches}")
}


