#!/bin/zsh

_fzf_complete_yay() {
  local lbuf preview get_matches flags
  lbuf="$1"
  flags='--pacman /usr/bin/pacman'
  yay_exec="yay ${flags}"
  preview="${yay_exec} -Si {1}"
  get_matches="${yay_exec} -Slq"
  if [[ "${lbuf}" == *-R* ]] || [[ "${lbuf}" == *--remove* ]]; then
    preview="${yay_exec} -Qi {1}"
    get_matches="${yay_exec} -Qq"
  fi
  _fzf_complete --height="${FZF_TMUX_HEIGHT:=75%}" --multi --ansi \
    --bind='Ctrl-X:toggle-preview' \
    --no-hscroll --inline-info \
    --header='Ctrl-X to toggle package info' \
    --preview-window='right:wrap' \
    --preview="${preview}" -- "$@" < <(eval "${get_matches}")
}

