#!/bin/zsh

_fzf_complete_yay() {
  local lbuf preview get_matches
  lbuf="$1"
  preview='yay -Si {1}'
  get_matches='yay -Pc | cut -f1'
  if [[ "${lbuf}" == *-R* ]] || [[ "${lbuf}" == *--remove* ]]; then
    preview='yay -Qi {1}'
    get_matches='yay -Qq'
  fi
  _fzf_complete --height="${FZF_TMUX_HEIGHT:=75%}" --multi --ansi \
    --bind='Ctrl-X:toggle-preview' \
    --no-hscroll --inline-info \
    --header='Ctrl-X to hide package info' \
    --preview="${preview}" -- "$@" < <(eval "${get_matches}")
}

